service: serverless-minerva-analysis-gating

provider:
    name: aws
    tags:
        project: minerva
    runtime: python3.8
    stage: ${opt:stage, "dev"}
    region: us-east-1
    memorySize: 128

plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
    wsgi:
        app: minerva_analysis.app
        packRequirements: false

functions:
    app:
        handler: wsgi_handler.handler
        events:
            - http: ANY /
            - http: 'ANY {proxy+}'
